; Switch from normal pico setup of platform io to more available pico W platform
[env:rpipicow]
platform  = https://github.com/maxgerhardt/platform-raspberrypi.git
board     = rpipicow
framework = arduino
; To ensure proper wifi capabilities we need a good core
board_build.core = earlephilhower
; To read at the same speed as the esp
monitor_speed = 115200
upload_protocol = mbed
upload_port = D:


; Decided to add the DHT11 so these libraries need to be included
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit BMP280 Library
    adafruit/Adafruit Unified Sensor @ ^1.1.14